name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
        docker login --username AWS --password-stdin 507660350427.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Push Docker Image
      run: |
        docker build -t flask-api .
        docker tag flask-api:latest 507660350427.dkr.ecr.us-east-1.amazonaws.com/flask-api:latest
        docker push 507660350427.dkr.ecr.us-east-1.amazonaws.com/flask-api:latest

    - name: Deploy on EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 507660350427.dkr.ecr.us-east-1.amazonaws.com
          
          docker stop flask-api || true
          docker rm flask-api || true
          
          docker pull 507660350427.dkr.ecr.us-east-1.amazonaws.com/flask-api:latest
          
          docker run -d -p 80:5000 --name flask-api \
          507660350427.dkr.ecr.us-east-1.amazonaws.com/flask-api:latest
